M48
; DRILL file {KiCad (6.0.0)} date Fri Dec 30 16:33:43 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-30T16:33:43+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.8364Y-1.6234
X1.8364Y-4.2022
X6.6415Y-1.6234
X6.6415Y-4.2022
T0
M30
